### PR TITLE
update rfc: chaos dashboard does not hold any permission, also not create new user

### PR DESCRIPTION
**Pull request by STRRL**
As https://github.com/chaos-mesh/rfcs/issues/5 says, chaos dashboard should not keep any permissions.

For features about creating new user, we need more talk. https://github.com/chaos-mesh/rfcs/issues/7

Rendered markdown: [link]( https://github.com/STRRL/rfcs/blob/main/text/2020-10-22-authn-and-authz-on-chaos-dashboard.md)

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL @cwen0 @WangXiangUSTC @YangKeao

**Comment by WangXiangUSTC** [comment]
dashboard should not have the privileges to create user, but the token user used to login in can have this privilege.
We can delete it now, but we may add the function of creating user later.

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
