### PR TITLE
logging: update tldr section about "which level should I use"

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <str_ruiling@outlook.com>

### CODE REVIEW

**Comment by STRRL** [comment]
PTAL

/cc @iguoyr @chaos-mesh/committers  @chaos-mesh/maintainers

**Review by iguoyr — APPROVED** [review]
LGTM

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Pull request merged**
