### PR TITLE
extensible chaosctl

### PR DESCRIPTION
**Pull request by Hexilee**
Signed-off-by: hexilee <i@hexilee.me>

A tool to control the status of Chaos Mesh as much as possible in an extensible way. Here is the [rendered markdown](https://github.com/Hexilee/rfcs/blob/chaosctl/text/2021-07-23-extensible-chaosctl.md).

### CODE REVIEW

**Comment by STRRL** [comment]
basically LGTM, expect one question: where do we implement the API server? 

It is part of  `chaos-daemon`?( chaos-daemon is the nearest component for the info of `iptables/ipset/cgroup/procfs` ) 

Or a new component?

**Comment by Hexilee** [comment]
> 
> 
> basically LGTM, expect one question: where do we implement the API server?
> 
> It is part of `chaos-daemon`?( chaos-daemon is the nearest component for the info of `iptables/ipset/cgroup/procfs` )
> 
> Or a new component?

We need a new component, as the node hosting identified container is uncertain. The API server will deliver requests of lower-level resources like `iptables/ipset/cgroup/procfs` to chaos-daemon on the host node.

**Review by YangKeao — COMMENTED** [review]
LGTM.

For the question: "where do we implement the API server?" I prefer to integrate the api server into the `chaos-controller-manager`, and run it out of box (but not a standalone component).

In the future (could be a long long long future), maybe we will provide these information in the dashboard to help the users to get rich debug information without having to use the CLI. @g1eny0ung Do you have any opinion on this RFC?

**Comment by Hexilee** [comment]
> 
> 
> LGTM.
> 
> For the question: "where do we implement the API server?" I prefer to integrate the api server into the `chaos-controller-manager`, and run it out of box (but not a standalone component).
> 
> In the future (could be a long long long future), maybe we will provide these information in the dashboard to help the users to get rich debug information without having to use the CLI. @g1eny0ung Do you have any opinion on this RFC?

I agree with you.

**Review by STRRL — APPROVED** [review]
LGTM!

**Pull request merged**
